import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%OAK_AGENT_HOOK_PORT%"=="" if defined OAK_AGENT_HOOK_ENDPOINT if exist "%OAK_AGENT_HOOK_ENDPOINT%" call "%OAK_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%OAK_AGENT_HOOK_TOKEN%"=="" if not "%OAK_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      'if "%OAK_AGENT_HOOK_PORT%"=="" exit /b 0',
      'if "%OAK_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'if "%OAK_PANE_KEY%"=="" exit /b 0',
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\oak-dev\\agent-hooks" for /r "%APPDATA%\\oak-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%OAK_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\oak\\agent-hooks" for /r "%APPDATA%\\oak\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%OAK_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set OAK_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%OAK_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    '__oak_read_ancestor_var() {',
    '  __oak_name="$1"',
    '  __oak_pid="${PPID:-}"',
    '  while [ -n "$__oak_pid" ] && [ "$__oak_pid" != "0" ] && [ "$__oak_pid" != "1" ]; do',
    '    __oak_value=""',
    '    if [ -r "/proc/$__oak_pid/environ" ]; then',
    '      __oak_value=$(tr "\\000" "\\n" < "/proc/$__oak_pid/environ" 2>/dev/null | sed -n "s/^${__oak_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__oak_value" ]; then',
    '      __oak_value=$(ps eww -p "$__oak_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__oak_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__oak_value" ]; then',
    '      printf "%s\\n" "$__oak_value"',
    '      return 0',
    '    fi',
    '    __oak_pid=$(ps -o ppid= -p "$__oak_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__oak_fill_from_ancestor() {',
    '  __oak_name="$1"',
    '  case "$__oak_name" in',
    '    OAK_AGENT_HOOK_ENDPOINT) [ -z "${OAK_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    OAK_AGENT_HOOK_PORT) [ -z "${OAK_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    OAK_AGENT_HOOK_TOKEN) [ -z "${OAK_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    OAK_AGENT_HOOK_ENV) [ -z "${OAK_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    OAK_AGENT_HOOK_VERSION) [ -z "${OAK_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    OAK_PANE_KEY) [ -z "${OAK_PANE_KEY:-}" ] || return 0 ;;',
    '    OAK_TAB_ID) [ -z "${OAK_TAB_ID:-}" ] || return 0 ;;',
    '    OAK_WORKTREE_ID) [ -z "${OAK_WORKTREE_ID:-}" ] || return 0 ;;',
    '    OAK_AGENT_LAUNCH_TOKEN) [ -z "${OAK_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __oak_value=$(__oak_read_ancestor_var "$__oak_name") || return 0',
    '  [ -n "$__oak_value" ] && export "$__oak_name=$__oak_value"',
    '}',
    '__oak_endpoint_value() {',
    '  __oak_endpoint_name="$1"',
    '  __oak_endpoint_path="$2"',
    '  sed -n "s/^${__oak_endpoint_name}=//p" "$__oak_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__oak_fill_from_endpoint_file() {',
    '  __oak_endpoint_path="$1"',
    '  [ -r "$__oak_endpoint_path" ] || return 0',
    '  __oak_endpoint_port=$(__oak_endpoint_value OAK_AGENT_HOOK_PORT "$__oak_endpoint_path")',
    '  if [ -n "${OAK_AGENT_HOOK_PORT:-}" ] && [ -n "$__oak_endpoint_port" ] && [ "$__oak_endpoint_port" != "$OAK_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __oak_endpoint_name in OAK_AGENT_HOOK_PORT OAK_AGENT_HOOK_TOKEN OAK_AGENT_HOOK_ENV OAK_AGENT_HOOK_VERSION; do',
    '    eval "__oak_current=\\${$__oak_endpoint_name:-}"',
    '    [ -z "$__oak_current" ] || continue',
    '    __oak_endpoint_value=$(__oak_endpoint_value "$__oak_endpoint_name" "$__oak_endpoint_path")',
    '    [ -n "$__oak_endpoint_value" ] && export "$__oak_endpoint_name=$__oak_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Oak pane/hook metadata, so recover it before posting.',
    'for __oak_name in OAK_AGENT_HOOK_ENDPOINT OAK_AGENT_HOOK_PORT OAK_AGENT_HOOK_TOKEN OAK_AGENT_HOOK_ENV OAK_AGENT_HOOK_VERSION OAK_PANE_KEY OAK_TAB_ID OAK_WORKTREE_ID OAK_AGENT_LAUNCH_TOKEN; do',
    '  __oak_fill_from_ancestor "$__oak_name"',
    'done',
    'if [ -n "$OAK_AGENT_HOOK_ENDPOINT" ] && [ -r "$OAK_AGENT_HOOK_ENDPOINT" ]; then',
    '  __oak_fill_from_endpoint_file "$OAK_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# OAK_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$OAK_AGENT_HOOK_TOKEN" ] && [ -n "$OAK_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/oak-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/oak-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/oak-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/oak-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/oak/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/oak/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^OAK_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$OAK_AGENT_HOOK_PORT" ]; then',
    '      __oak_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$OAK_AGENT_HOOK_PORT" ] || [ -z "$OAK_AGENT_HOOK_TOKEN" ] || [ -z "$OAK_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    'payload=$(cat)',
    'if [ -z "$payload" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    'curl -sS -X POST "http://127.0.0.1:${OAK_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Oak-Agent-Hook-Token: ${OAK_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${OAK_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${OAK_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${OAK_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${OAK_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${OAK_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${OAK_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload=${payload}" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
